# Generated by Django 5.2.11 on 2026-02-19 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='railwaygate',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
